Algoritmo "atividade15 manzano"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/03/2022
Var
// Seção de Declarações das variáveis 
valor:inteiro

Inicio
Escreval("Digite um valor:")
Leia(valor)
se valor<0 entao
Escreval("É negativo")
senao
Escreval("É positivo")
fimse
Fimalgoritmo